#!/usr/bin/env ruby

require "dynflow_sbx"

module DynflowSbx
  class << self
    def main
      DynHelper.world.trigger Actions::MultiExternalActionPlanner
      DynHelper.run_web_console
    end
  end
end

if $0 == __FILE__
  DynflowSbx::main
end
